### ISSUE TITLE
Plugin does not support UNC paths

### ISSUE THREAD

**Issue by jobbojobson** [oviradoi/npp-explorer-plugin#35] opened 2023-01-03 13:53 UTC
Plugin seems unable to navigate to UNC paths.

"Go To Path..." does not give an error when presented with a UNC path, it just silently fails to navigate to the path.

**Comment by oviradoi** [comment] 2023-01-03 13:55
This is a duplicate of issue #34 

The plugin does not support UNC paths

**Closed by oviradoi** 2023-01-03 13:55 UTC
