### ISSUE TITLE
Error when installing via NPP Plugin manager

### ISSUE THREAD

**Issue by drsparksMS** [oviradoi/npp-explorer-plugin#3] opened 2019-05-21 17:26 UTC
When trying to install via the NPP Plugin Manager, I get an error about the hash not being what was expected.  See screenshot for more details. 

I'm running the 32-bit version of NPP, so not sure if this is expected or not.

![Annotation 2019-05-21 102223](https://user-images.githubusercontent.com/49798379/58117185-d9347680-7bb2-11e9-87b0-4125141a7169.png)

**Comment by talley** [comment] 2019-05-24 13:06
I got the same error.What a nice plugin but i cant use it

**Comment by AntonDevil** [comment] 2019-05-30 01:06
The problem is that Explorer.zip for 1.8.5 doesn't exist on the server. I'm not sure what exactly gets hashed, but certainly not the zip it was looking for.
[Explorer.zip 1.8.5](https://github.com/oviradoi/npp-explorer-plugin/releases/download/v1.8.6/Explorer.zip)
But author has updated the plugin to 1.8.6 and these links are working.
You can check plugin version, link, hash etc. in the [nppPluginList repo](https://github.com/notepad-plus-plus/nppPluginList/blob/d9f87669b7d52b05244bf4b5d54dcd98bd8be205/src/pl.x86.json#L290)
To deal with this problem you can manually update/install the plugin. Just put **Explorer.dll** here c:\Program Files (x86)\Notepad++\plugins\\**Explorer**\\**Explorer.dll**

**Comment by SullyPanda76cl** [comment] 2019-06-08 13:17
where do I find the **Explorer.dll** file?

**Comment by oviradoi** [comment] 2019-06-10 16:45
I made a mistake while trying to fix a bug in the plugin, and that caused the binaries for version 1.8.5 to get deleted from github. I have uploaded version 1.8.6 and I sent a pull request to the notepad++ team, and it will get added to the plugin manager when they make their next release.

So for now, if you want to use the plugin you will have to install it manually. The 1.8.6 version will be added to the plugin manager when the notepad++ team makes their next release.

**Comment by oviradoi** [comment] 2019-06-21 09:03
[Notepad++ 7.7.1](https://notepad-plus-plus.org/news/notepad-7.7.1-released.html) was released yesterday. 

It includes a new version of the plugin admin which has correct download links. This error should be fixed if you update to Notepad++ 7.7.1.

**Closed by oviradoi** 2019-06-21 09:03 UTC
